#!/usr/bin/env bash

set -e
set -o nounset
set -o pipefail

target="$1"
count=100

trap exit SIGINT

if [ -z "$target" ]; then
  echo "usage: $0 <target to ping>"
  exit
fi

while [ "$count" -ne 0 ]; do
  ping -c 1 "$target" >/dev/null
  rc=$?
  if [ "$rc" -eq 0 ]; then
    duration=$SECONDS
    count=1
  fi
  ((count = count - 1))
done

if [[ "$rc" -eq 0 ]]; then
  echo "$target is up again after $duration seconds."
  say "$target is up again."
else
  echo "Timeout after $count retries and $duration seconds."
  say "Timeout after $count retries and $duration seconds."
fi
