#!/usr/bin/env bash

set -o nounset -o errexit -o pipefail

file_name="$(mktemp /tmp/rbac-tool.XXXXX)"
namespace="${1:-}"

parameters="--exclude-namespaces="
if [ "$namespace" != "" ]; then
     parameters="--include-namespaces $namespace"
     parameters+=" --exclude-namespaces=*"
fi

which -s rbac-tool ||
     curl https://raw.githubusercontent.com/alcideio/rbac-tool/master/download.sh | BINDIR="$HOME/.bin" bash

rbac-tool vis $parameters \
     --show-legend --outformat dot \
     --outfile "$file_name".dot

dot -Tpng "$file_name".dot -Grankdir=LR -o "$file_name".png

open "$file_name".png
sleep 2 && rm -f "$file_name"*
