#!/bin/bash

# use these aliases
# alias env_test="~/.bin/ubuntu-env test"
# alias env_load="~/.bin/ubuntu-env load"
# alias env_save="~/.bin/ubuntu-env save"
# alias env_inst="~/.bin/ubuntu-env inst"

# You don't need to change anything below this line;)
tmp=$(mktemp -t XXXX)
backup="/tmp/backup-$(hostname).tar.gz"

set -e

usage () {
  echo "Usage:"
  echo "  $0 [OPTIONS]"
  echo "Options:"
  echo "  -h      : display this help message"
  echo "  -v      : verbose output"
  echo "Commands:"
  echo "  save    : save env in backup file"
  echo "  load    : load env from backup file"
  echo "  inst    : install all env packages"
}

log () {
  date=$(date -Iseconds)
  echo -e "$date $1" | fold -w70 -s | sed '2~1s/^/  /' 2>&1
}

env_test () {
  log "testing env ..."
  test -r "$backup" || ( log "ERROR: file '$backup' is not readable"; exit 1)
  tar -tzf "$backup" $files > $tmp 2>&1
  [ $verbose ] && cat $tmp
  stat "$backup" --printf='file:     %n\nmodified: %y\nbytes:    %s\n'
  log "done."
}

env_load () {
  log "loading env ..."
  test -r "$backup" || ( log "ERROR: file '$backup' is not readable"; exit 1)
  tar -xzf "$backup" $files && log "done."
}

env_save () {
  log "saving env ..."
  # create a list of manually installed packages (restore: sudo apt-get -y install < .install/packages-manual)
  apt-mark showmanual > .install/packages-manual
  # create a list of installed packages (restore: sudo dpkg --set-selections < .install/packages-list)
  dpkg --get-selections > .install/packages-list
  # create backup
  touch "$backup"
  test -w "$backup" || ( log "ERROR: file '$backup' is not readable"; exit 1)
  tar -cvzf "$backup" $files | tee $tmp | cut -f1 -d / | uniq
  [ $verbose ] && cat $tmp
  log "done."
}

env_inst () {
  log "installing env ..."
  # Run all install scripts
  for i in $(ls -t1 .install/install-*.sh); do
    log "executing $i ..."
    sudo bash $i $2
    log "finished $i ..."
  done
  # Run apt-get with package list
  sudo apt-get -y install $(cat .install/packages-manual)
  log "done."
}

# MAIN
while getopts "hv" opt; do
    case "$opt" in
       h) usage; exit 0 ;;
       v) verbose=1; set -xv;;
       *) log "ERROR: invalid option '$1'"; usage; exit 1 ;;
    esac
done
shift $((OPTIND-1))
args="$@"

pushd $HOME >/dev/null
files=$(ls -d1 .[a-zA-Z]* | egrep -v '\.bundle/cache|\.chefdk|\..*cache.*|\.local')
case "$args" in
  save) env_save; env_test;;
  load) env_test; env_load;;
  inst) env_test; env_inst;;
  test) env_test;;
  *) log "ERROR: invalid command '$1'"; usage; exit 1 ;;
esac
rm -f $tmp
popd >/dev/null
