#!/bin/bash

set -eo pipefail

instances="dockerhost"

for instance in $instances; do
  (multipass delete $instance >/dev/null 2>&1; multipass purge) || true
  multipass launch ubuntu --name $instance --cpus 2 --mem 2G --disk 4G || true
  multipass info $instance

  multipass exec $instance 'sudo apt-get update && sudo apt-get install -y apt-transport-https'
  multipass exec $instance 'sudo apt-get -y dist-upgrade'
  multipass exec $instance 'curl https://releases.rancher.com/install-docker/18.09.sh | sh'
  multipass exec $instance 'sudo usermod -aG docker ubuntu'
  multipass exec $instance 'sudo apt -y autoremove'
done
