#!/usr/bin/env bash

set -eo pipefail

# make files in ~/.dotfiles available
echo "--> linking ~/.dotfiles to $HOME/"
pushd ~/.dotfiles >/dev/null
for i in $(find . -type f -name '.[a-zA-Z]*'); do
    test -f "$(pwd)/$i" &&
        ln -sf "$(pwd)/$i" "$HOME"/
done
popd >/dev/null

echo "--> linking Oh My Zsh custom"
for subdir in plugins themes; do
    pushd "$HOME"/.dotfiles/.oh-my-zsh/custom/$subdir/ >/dev/null
    ln -sf $(pwd)/* "$HOME"/.oh-my-zsh/custom/$subdir
done
popd >/dev/null

## create SSH directory
install -d -m 700 ~/.ssh

# defaults Location for Screenshots
defaults write com.apple.screencapture location ~/Downloads

# defaults Autohide Dock
defaults write com.apple.dock autohide -bool true

mkdir -p "$HOME/.local"

# iTerm shell integration
curl -L https://iterm2.com/shell_integration/install_shell_integration_and_utilities.sh | bash

echo "--> FINISHED"
