#!/usr/bin/env bash

set -eo pipefail

# make files in ~/.dotfiles available
echo "--> linking ~/.dotfiles to $HOME/"
pushd ~/.dotfiles >/dev/null
ln -sf "$(pwd)"/.[a-zA-Z]* "$HOME"/
popd >/dev/null

echo "--> linking ~/.dotfiles/.bin to $HOME/"
pushd ~/.dotfiles/.bin >/dev/null
ln -sf "$(pwd)"/.bin "$HOME"/
popd >/dev/null

echo "--> linking Oh My Zsh custom"
pushd ~/.dotfiles/oh-my-zsh >/dev/null
ln -sf custom ../../.oh-my-zsh
popd >/dev/null

## create SSH directory
install -d -m 660 ~/.ssh

# defaults Location for Screenshots
defaults write com.apple.screencapture location ~/Downloads

# defaults Autohide Dock
defaults write com.apple.dock autohide -bool true

# install things not available via brew
# awshelper
pip3 install awshelper https://codeload.github.com/boto/botocore/zip/v2
# iTerm shell iintegration
curl -L https://iterm2.com/shell_integration/install_shell_integration_and_utilities.sh | bash
