#!/bin/bash
# setup: copy dotfiles to your home and configure (executed by strap.sh)

set -exo pipefail

pushd ~/.dotfiles > /dev/null
echo "copying dotfiles ..."
rsync --exclude ".git/" \
  --exclude ".DS_Store" \
  --exclude "script/" \
  --exclude ".oh-my-zsh" \
  --exclude "*.md" \
  --exclude "*.txt" \
  -avh --no-perms -n . ~;
popd > /dev/null

# configure Git on macOS to properly handle line endings
git config --global core.autocrlf input

# set macOS Location for Screenshots
defaults write com.apple.screencapture location ~/Downloads 
